# Generated by Django 5.1.4 on 2026-06-12 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('hostel', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_beds', to='students.student'),
        ),
        migrations.AddField(
            model_name='building',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_buildings', to='core.school'),
        ),
        migrations.AddField(
            model_name='building',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warden_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hostel.building'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='allocated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_allocations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='hostel.bed'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='students.student'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.floor'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.room'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('floor', 'room_number')},
        ),
    ]
