# Generated by Django 5.1.4 on 2026-06-12 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiver',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_waivers', to='students.student'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feecategory'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.school'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='core.school'),
        ),
        migrations.AddField(
            model_name='studentscholarship',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='studentscholarship',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scholarships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentscholarship',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scholarships', to='finance.scholarship'),
        ),
        migrations.AddField(
            model_name='studentscholarship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='feecategory',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'academic_year', 'class_obj', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='studentscholarship',
            unique_together={('student', 'scholarship', 'academic_year')},
        ),
    ]
