# Generated by Django 5.1.4 on 2026-06-12 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('attended', 'Attended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'detentions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplineIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('witnesses', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, upload_to='discipline/evidence/')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='reported', max_length=15)),
                ('action_taken', models.CharField(blank=True, choices=[('warning', 'Warning'), ('detention', 'Detention'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion'), ('counseling', 'Counseling'), ('parent_meeting', 'Parent Meeting'), ('community_service', 'Community Service'), ('other', 'Other')], max_length=20)),
                ('action_details', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discipline_incidents',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('suspension_type', models.CharField(choices=[('in_school', 'In-School'), ('out_of_school', 'Out of School')], max_length=15)),
                ('conditions_for_return', models.TextField(blank=True)),
                ('parent_acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'suspensions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BehaviorCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity_level', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('severe', 'Severe')], max_length=10)),
                ('points_deducted', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_categories', to='core.school')),
            ],
            options={
                'verbose_name_plural': 'Behavior Categories',
                'db_table': 'behavior_categories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BehaviorPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_points', models.IntegerField(default=0)),
                ('positive_points', models.PositiveIntegerField(default=0)),
                ('negative_points', models.PositiveIntegerField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_points', to='core.academicyear')),
            ],
            options={
                'verbose_name_plural': 'Behavior Points',
                'db_table': 'behavior_points',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
