# Generated by Django 5.1.4 on 2026-06-12 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('discipline', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorpoints',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_points', to='students.student'),
        ),
        migrations.AddField(
            model_name='detention',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detentions', to='students.student'),
        ),
        migrations.AddField(
            model_name='detention',
            name='supervised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_detentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='discipline.behaviorcategory'),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_discipline_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discipline_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_incidents', to='core.school'),
        ),
        migrations.AddField(
            model_name='disciplineincident',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_incidents', to='students.student'),
        ),
        migrations.AddField(
            model_name='detention',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detentions', to='discipline.disciplineincident'),
        ),
        migrations.AddField(
            model_name='suspension',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_suspensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspension',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions', to='discipline.disciplineincident'),
        ),
        migrations.AddField(
            model_name='suspension',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='behaviorpoints',
            unique_together={('student', 'academic_year')},
        ),
    ]
