# Generated by Django 5.1.4 on 2026-06-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to='students.student'),
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionapplication'),
        ),
        migrations.AddField(
            model_name='admissionperiod',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_periods', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='admissionperiod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_periods', to='core.school'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='admission_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.admissionperiod'),
        ),
        migrations.AddField(
            model_name='seatallocation',
            name='admission_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='admissions.admissionperiod'),
        ),
        migrations.AddField(
            model_name='seatallocation',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='academics.class'),
        ),
        migrations.AlterUniqueTogether(
            name='seatallocation',
            unique_together={('admission_period', 'class_obj')},
        ),
    ]
