# Generated by Django 5.1.4 on 2026-06-12 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exam_types',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_letter', models.CharField(blank=True, max_length=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_absent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter', models.CharField(max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'grade_ranges',
                'ordering': ['-min_percentage'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grading_scales',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('teacher_comments', models.TextField(blank=True)),
                ('principal_comments', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('generated_file', models.FileField(blank=True, upload_to='report_cards/')),
            ],
            options={
                'db_table': 'report_cards',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.term')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=33, max_digits=5)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examinations.exam')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academics.subject')),
            ],
            options={
                'db_table': 'exam_schedules',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamSeatingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_number', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=50)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='examinations.examschedule')),
            ],
            options={
                'db_table': 'exam_seating_plans',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
