# Generated by Django 5.1.4 on 2026-06-12 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('table', 'Table'), ('metric', 'Metric'), ('list', 'List')], max_length=10)),
                ('data_source', models.CharField(help_text='API endpoint or query identifier', max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Chart type, colors, etc.')),
                ('position', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(help_text='Which role sees this widget', max_length=50)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('academic', 'Academic'), ('financial', 'Financial'), ('attendance', 'Attendance'), ('hr', 'HR'), ('custom', 'Custom')], max_length=15)),
                ('query', models.TextField(help_text='SQL or query parameters')),
                ('parameters', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('schedule', models.CharField(blank=True, help_text='Cron expression for scheduled reports', max_length=100)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('parameters_used', models.JSONField(default=dict)),
                ('result_file', models.FileField(blank=True, upload_to='reports/results/')),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'report_executions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction_type', models.CharField(choices=[('dropout_risk', 'Dropout Risk'), ('performance', 'Performance'), ('attendance', 'Attendance')], max_length=15)),
                ('prediction_date', models.DateField()),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factors', models.JSONField(default=dict)),
                ('recommendation', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_predictions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='core.school')),
            ],
            options={
                'db_table': 'ai_predictions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
